(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'SQLFORM' object has no attribute 'chave'"
p3
sS'layer'
p4
S'/home/volney/Projetos/web2py/web2py/applications/CifraDeCesar/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f1074035330, file "/home/volney/Projetos/web2py/web2py/applications/CifraDeCesar/controllers/default.py", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/volney/Projetos/web2py/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/volney/Projetos/web2py/web2py/applications/CifraDeCesar/controllers/default.py", line 98, in <module>\n  File "/home/volney/Projetos/web2py/web2py/gluon/globals.py", line 414, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/volney/Projetos/web2py/web2py/applications/CifraDeCesar/controllers/default.py", line 21, in index\n    IS_INT_IN_RANGE(0, 320, error_message=\'Precisa ser um n\xc3\xbamero ente 0 e 320!\')\nAttributeError: \'SQLFORM\' object has no attribute \'chave\'\n'
p11
s.